logLevel: DEBUG
serverRootPath: /api/attributes
openapiUrl: /openapi
serverPublicName: "Attribute Authority"
serverCorsOrigins: "*"
oidc:
  clientId: tdf-attributes
  externalHost: http://offline.demo.internal/auth
  internalHost: http://keycloak-http/auth
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  className: nginx
  hosts:
    localhost: &paths
      "/api/attributes(/|$)(.*)":
        pathType: Prefix
    host.docker.internal: *paths
    offline.demo.internal: *paths
    opentdf.local: *paths
postgres:
  host: postgresql
  port: 5432
  user: tdf_attribute_manager
  database: tdf_database
  schema: tdf_attribute
secretRef:
  name: opentdf-attributes-secrets
