serverRootPath: /api/entitlements
publicName: "Entitlement"
serverCorsOrigins: "*"
openapiUrl: /openapi
logLevel: DEBUG
postgres:
  host: postgresql
  port: 5432
  user: tdf_entitlement_manager
  password: bXlQb3N0Z3Jlc1Bhc3N3b3Jk
  database: tdf_database
  schema: tdf_entitlement
oidc:
  clientId: tdf-entitlement
  clientSecret: myclientsecret
  realm: tdf
  #    trailing / is required
  serverUrl: http://keycloak-http/auth/
  configurationUrl: http://keycloak-http/auth/realms/tdf/.well-known/openid-configuration
  authorizationUrl: http://offline.demo.internal/auth/realms/tdf/protocol/openid-connect/auth
  tokenUrl: http://offline.demo.internal/auth/realms/tdf/protocol/openid-connect/token
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  className: nginx
  hosts:
    localhost: &paths
      "/api/entitlements(/|$)(.*)":
        pathType: Prefix
    host.docker.internal: *paths
    offline.demo.internal: *paths
    opentdf.local: *paths
secretRef:
  name: opentdf-entitlements-secrets
